import { TEAM_MAPPING } from './data.mjs';
import { fetchJson, ProviderError } from './http.mjs';
const API_FOOTBALL_BASE=(process.env.API_FOOTBALL_BASE||'https://v3.football.api-sports.io').replace(/\/$/,'');const ODDS_API_BASE=(process.env.ODDS_API_BASE||'https://api.the-odds-api.com/v4').replace(/\/$/,'');const teamIdCache=new Map(),liveFootballCache=new Map();
export function liveDataEnabled(){return !['0','false','no','off'].includes(String(process.env.LIVE_DATA_ENABLED||'true').toLowerCase());}
export function normName(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');}
export function getOddsTeamName(sport,team){return TEAM_MAPPING?.[sport]?.[team]?.odds_name||team;}
export function getOddsSportKey(sport,a,b){const env={cz_football:'ODDS_SPORT_CZ_FOOTBALL',fifa:'ODDS_SPORT_FIFA',nba:'ODDS_SPORT_NBA',nhl:'ODDS_SPORT_NHL'};if(process.env[env[sport]])return process.env[env[sport]];if(sport==='nba')return'basketball_nba';if(sport==='nhl')return'icehockey_nhl';if(sport==='fifa'){const x=TEAM_MAPPING?.fifa?.[a]?.odds_sport_key,y=TEAM_MAPPING?.fifa?.[b]?.odds_sport_key;return x&&x===y?x:null;}return null;}
export async function apiFootball(endpoint,params={}){const key=process.env.API_FOOTBALL_KEY;if(!key)throw new ProviderError('Chybí API_FOOTBALL_KEY v Netlify environment variables.',{status:503,code:'MISSING_KEY'});const url=new URL(`${API_FOOTBALL_BASE}/${String(endpoint).replace(/^\//,'')}`);for(const[k,v]of Object.entries(params))url.searchParams.set(k,String(v));const{data}=await fetchJson(url,{headers:{'x-apisports-key':key}},'API-Football');if(data?.errors&&Object.keys(data.errors).length)throw new ProviderError('API-Football vrátilo chybu.',{status:502,code:'API_FOOTBALL_ERROR'});return data;}
export async function resolveApiFootballTeamId(sport,team){const ck=`${sport}:${team}`;if(teamIdCache.has(ck))return teamIdCache.get(ck);const search=TEAM_MAPPING?.[sport]?.[team]?.api_football_search||team,p=await apiFootball('teams',{search}),rows=p?.response||[];if(!rows.length)throw new ProviderError(`API-Football nenašel tým '${team}'.`,{status:404,code:'TEAM_NOT_FOUND'});const exact=rows.find(r=>String(r?.team?.name||'').toLowerCase()===search.toLowerCase()),id=Number((exact||rows[0])?.team?.id);teamIdCache.set(ck,id);return id;}
export async function loadLiveFootballTeamData(sport,team,fallback){const ck=`${sport}:${team}`;if(liveFootballCache.has(ck))return liveFootballCache.get(ck);const id=await resolveApiFootballTeamId(sport,team),p=await apiFootball('fixtures',{team:id,last:Number(process.env.API_FOOTBALL_RECENT_MATCHES||10)}),scored=[],conceded=[];for(const item of p?.response||[]){const h=item?.teams?.home?.id,a=item?.teams?.away?.id,hg=item?.goals?.home,ag=item?.goals?.away;if(hg==null||ag==null)continue;if(h===id){scored.push(Number(hg));conceded.push(Number(ag));}else if(a===id){scored.push(Number(ag));conceded.push(Number(hg));}}if(scored.length<3)throw new ProviderError(`Málo dokončených zápasů pro '${team}'.`,{status:422,code:'NOT_ENOUGH_MATCHES'});const avg=x=>x.reduce((a,b)=>a+b,0)/x.length,r={attack:avg(scored),defense:avg(conceded),home_adv:fallback.home_adv||.12,matches_used:scored.length};liveFootballCache.set(ck,r);return r;}
export async function fetchOddsEvents(key){const api=process.env.ODDS_API_KEY;if(!api)throw new ProviderError('Chybí ODDS_API_KEY v Netlify environment variables.',{status:503,code:'MISSING_KEY'});const u=new URL(`${ODDS_API_BASE}/sports/${key}/events`);u.searchParams.set('apiKey',api);u.searchParams.set('dateFormat','iso');return(await fetchJson(u,{},'The Odds API')).data;}
export async function fetchEventOdds(key,id,markets='h2h,spreads,totals',regions=null){const api=process.env.ODDS_API_KEY;if(!api)throw new ProviderError('Chybí ODDS_API_KEY v Netlify environment variables.',{status:503,code:'MISSING_KEY'});const u=new URL(`${ODDS_API_BASE}/sports/${key}/events/${id}/odds`);u.searchParams.set('apiKey',api);u.searchParams.set('regions',regions||process.env.ODDS_REGIONS||'eu');u.searchParams.set('markets',markets);u.searchParams.set('oddsFormat','decimal');u.searchParams.set('dateFormat','iso');const{data,response}=await fetchJson(u,{},'The Odds API');return{data,usage:{requests_remaining:response.headers.get('x-requests-remaining'),requests_used:response.headers.get('x-requests-used'),requests_last:response.headers.get('x-requests-last')}};}
export function findOddsEvent(events,sport,a,b){const wanted=new Set([normName(getOddsTeamName(sport,a)),normName(getOddsTeamName(sport,b))]);return(events||[]).find(e=>{const actual=new Set([normName(e?.home_team),normName(e?.away_team)]);return actual.size===wanted.size&&[...actual].every(v=>wanted.has(v));})||null;}
export function summarizeEventMarkets(event){const bookmakers=[],ml=new Map(),spreads=new Map(),totals=new Map(),push=(m,k,p)=>{if(!m.has(k))m.set(k,[]);m.get(k).push(p);};for(const b of event?.bookmakers||[]){const row={key:b.key,title:b.title,last_update:b.last_update,markets:{}};for(const m of b?.markets||[]){if(!['h2h','spreads','totals'].includes(m.key))continue;row.markets[m.key]=[];for(const o of m?.outcomes||[]){const item={name:o.name,price:o.price};if(typeof o.point==='number')item.point=o.point;row.markets[m.key].push(item);if(typeof o.price!=='number')continue;if(m.key==='h2h')push(ml,String(o.name),o.price);else if(m.key==='spreads'&&typeof o.point==='number')push(spreads,`${o.name}\0${o.point}`,o.price);else if(m.key==='totals'&&typeof o.point==='number')push(totals,`${o.name}\0${o.point}`,o.price);}}if(Object.keys(row.markets).length)bookmakers.push(row);}const avg=v=>Number((v.reduce((a,b)=>a+b,0)/v.length).toFixed(3));return{consensus:{moneyline:[...ml].map(([name,p])=>({name,average_price:avg(p),bookmakers:p.length})),spreads:[...spreads].map(([k,p])=>{const[name,point]=k.split('\0');return{name,point:Number(point),average_price:avg(p),bookmakers:p.length};}),totals:[...totals].map(([k,p])=>{const[name,point]=k.split('\0');return{name,point:Number(point),average_price:avg(p),bookmakers:p.length};})},bookmakers};}
export async function findMatchOdds({sport,teamA,teamB,markets='h2h,spreads,totals',regions=null}){if(!TEAM_MAPPING[sport])throw new TypeError('Nepodporovaný sport.');if(!teamA||!teamB||teamA===teamB)throw new TypeError('Zadej dva různé týmy.');const allowed=new Set(['h2h','spreads','totals']),requested=[...new Set(String(markets).split(',').map(v=>v.trim()).filter(Boolean))];if(!requested.length||requested.some(v=>!allowed.has(v)))throw new TypeError('markets může obsahovat pouze h2h, spreads a totals.');const key=getOddsSportKey(sport,teamA,teamB);if(!key)throw new TypeError(`Pro sport '${sport}' nelze určit The Odds API sport key. Nastav ODDS_SPORT_* environment variable.`);const event=findOddsEvent(await fetchOddsEvents(key),sport,teamA,teamB);if(!event){const e=new Error(`The Odds API nenašlo zápas ${teamA} vs ${teamB} pro sport key '${key}'.`);e.status=404;e.code='EVENT_NOT_FOUND';throw e;}if(!event.id)throw new ProviderError('Nalezený event nemá event ID.',{status:502,code:'MISSING_EVENT_ID'});const{data,usage}=await fetchEventOdds(key,String(event.id),requested.join(','),regions),summary=summarizeEventMarkets(data);return{sport,sport_key:key,requested_teams:{team_a:teamA,team_b:teamB},matched_event:{id:String(event.id),home_team:data.home_team||event.home_team,away_team:data.away_team||event.away_team,commence_time:data.commence_time||event.commence_time},markets_requested:requested,markets:summary.consensus,bookmakers:summary.bookmakers,api_usage:usage};}
